added duckduckgo
Carberra/Carberretta pull request #101
Opened 2021-05-22 19:30 UTC by helish88

2021-05-22 19:47 UTC, parafoxia commented
We don't accept PRs without a corresponding issue. Please create one.

2021-05-22 19:47 UTC, IkBenOlie5 commented
https://lmddgtfy.net/

Use this

2021-05-24 16:53 UTC, parafoxia requested changes

2021-05-24 16:53 UTC, parafoxia commented on carberretta/bot/cogs/links.py
> +    async def command_google(self, ctx: commands.Context, *, query: str) -> None:
```suggestion
    async def command_duckduckgo(self, ctx: commands.Context, *, query: str) -> None:
```

2021-05-24 16:53 UTC, parafoxia commented on carberretta/bot/cogs/links.py
> +        await ctx.send(f"<https://duckduckgo.com/?q={query.replace(' ', '+')}>")
It would be better to use https://lmddgtfy.net/, as it then fits in more with the `+google` command.

2021-05-24 17:54 UTC, helish88 commented on carberretta/bot/cogs/links.py
> +        await ctx.send(f"<https://duckduckgo.com/?q={query.replace(' ', '+')}>")
agree

2021-11-26 15:31 UTC, closed without merging