fix(possessive)
Carberra/Carberretta pull request #119
Opened 2021-09-02 03:30 UTC by remagnedlogeht

Make possessive not add the s if it ends with x, and also make it check the string lowercase instead of the raw string.

2021-09-02 07:32 UTC, parafoxia commented
Is not ending adding s if the name ends in x a rule? I don't remember that being a thing. The .lower fix would work though.

2021-09-11 16:06 UTC, parafoxia requested changes

2021-09-11 16:06 UTC, parafoxia commented on carberretta/utils/string.py
> +    return f"{name}'{'s' if not name.lower().endswith('s') or name.lower().endswith('x') else ''}"
I don't think this "x" thing is an actual rule.

2021-09-11 17:04 UTC, remagnedlogeht commented
> Is not ending adding s if the name ends in x a rule? I don't remember that being a thing. The .lower fix would work though.

well if my school says so some years ago :p

2021-11-26 15:31 UTC, closed without merging