Port gateway extension
Carberra/Carberretta pull request #130
Opened 2021-11-28 17:41 UTC by neonjonn

If possible, I'd like to keep this PR open while I attempt to add welcome cards as attachments to the welcome messages

2021-11-28 17:46 UTC, parafoxia commented
It looks like you might to rebase the commit chain. If you do the following commands, it *should* fix it:
```sh
git remote add upstream https://github.com/Carberra/Carberretta
git pull upstream main
git rebase
```

2021-11-28 17:48 UTC, parafoxia commented
Also, I'd prefer if you put the attachment images in a separate PR as the scopes are different. Though you can obvs just attach it to the code you wrote here. If you've done everything for porting, mark it as ready for review and I'll have a look-see.

2021-11-28 17:50 UTC, neonjonn commented
I'm still getting used to making PRs 😅

Did the rebase, never knew about that command before :0

And cool, I'll make another PR after adding the attachment code :)

2021-11-28 17:51 UTC, parafoxia commented
Yeah no worries haha, they can be a nightmare to do sometimes haha. It doesn't look like it did what I thought it might do, so I'll have a look and see if I can fix up the history a bit. You also need to fix the typing issue that's arising.

2021-11-28 17:53 UTC, neonjonn commented
I forgot to sync the commit, will do now so hopefully that fixes the rebase. And I almost never use mypy but I'll take a look at the typing issues now

2021-11-28 18:03 UTC, parafoxia commented
Damn, might have just messed up it completely lmao.

2021-11-28 18:04 UTC, neonjonn commented
Oh no...

2021-11-28 18:06 UTC, parafoxia commented
Okay that fixed it by the looks of it. Literally had to manually rebase about 7 commits but got there in the end lmao.

2021-11-28 18:07 UTC, neonjonn commented
Oh damn, well at least it's fixed now 😅

2021-11-28 18:09 UTC, parafoxia commented
Yeah 😆 I think it may have been my fault cos I did do a few rebases yesterday, so I think your downstream fork got caught up in that. To fix you downstream main though, you'll need to do:
```sh
git checkout main
git reset --hard HEAD~10
git pull upstream main
```
That won't affect your other branch.

2021-11-28 18:12 UTC, neonjonn commented
yeah that seemed to work, all looks good

2021-11-28 18:12 UTC, parafoxia commented
Sweet

2021-11-29 09:19 UTC, parafoxia requested changes
The typing seems to be okay now Lightbulb has updated, but you've made a typo that needs to be fixed. I'm on mobile atm but when I'm next on my computer I'll pull the changes down and test everything properly.

2021-11-29 09:19 UTC, parafoxia commented on carberretta/extensions/gateway.py
> +                if not m.bot
This should be `m.is_bot`.

2021-11-29 09:20 UTC, parafoxia commented
Also if you can change Lightbulb's min version from 2.0 to 2.0.2 that'd be ace.

2021-11-29 09:27 UTC, neonjonn commented
Cool, I'll make those changes now... and stop using GitHub Co-pilot, that's probably why I made that typo 😅

2021-11-29 09:36 UTC, parafoxia commented
Tfw Copilot doesn't even get it right. Probably used Carberretta's old code to get that result lmao.

2021-11-29 09:41 UTC, neonjonn commented
Probably XD, I had commented out the old code to reference it

2021-11-29 11:57 UTC, parafoxia requested changes
Haven't been able to do a proper test of the logic yet, but I think it should be okay after these changes. There are some differences between Hikari and discord.py that you need to address.

I also ask if you could port over the [patch introduced in v1.5.5](https://github.com/Carberra/Carberretta/commit/412b7269b8c4ed3872da883349f49f1f38f9f732), which fixes a problem related to cross-server gateway messages.

2021-11-29 11:57 UTC, parafoxia commented on carberretta/extensions/gateway.py
> +            Config.GATEWAY_ID,
```suggestion
            Config.GATEWAY_CHANNEL_ID,
```
Change to conform with new channel env standard.

2021-11-29 11:57 UTC, parafoxia commented on carberretta/extensions/gateway.py
> +            Config.GATEWAY_ID,
```suggestion
            Config.GATEWAY_CHANNEL_ID,
```
Change to conform with new channel env standard.

2021-11-29 11:57 UTC, parafoxia commented on carberretta/extensions/gateway.py
> +        if (secs := (dt.datetime.utcnow() - m.joined_at).seconds) <= TIMEOUT:
```suggestion
    now = dt.datetime.now().astimezone()
    
    async for m in plugin.bot.rest.fetch_members(Config.GUILD_ID):
        if (secs := (now - m.joined_at).seconds) <= TIMEOUT:
```
This needs to be changed as Hikari uses offset-aware datetime objects, unlike discord.py.

2021-11-29 12:37 UTC, neonjonn commented on carberretta/extensions/gateway.py
> +            Config.GATEWAY_ID,
Fixed

2021-11-29 12:37 UTC, neonjonn commented on carberretta/extensions/gateway.py
> +            Config.GATEWAY_ID,
Fixed too

2021-11-29 12:39 UTC, neonjonn commented on carberretta/extensions/gateway.py
> +        if (secs := (dt.datetime.utcnow() - m.joined_at).seconds) <= TIMEOUT:
Fixed as well, I wasn't aware Hikari did that

2021-11-29 12:54 UTC, neonjonn commented
I've applied those changes and copied across the stuff from v1.5.5 :)

2021-11-29 14:07 UTC, parafoxia submitted a review, later dismissed
These changes look good. I'm gonna add a few additional commits to account for some more differences in Hikari, plus add logging to it. But yeah, your job *should* be done now. Thanks!

2021-11-29 14:34 UTC, neonjonn commented
Cool, no problem!

2021-11-29 15:00 UTC, parafoxia approved these changes

2021-11-29 15:03 UTC, merged