Add welcome cards for welcome messages
Carberra/Carberretta pull request #138
Opened 2021-12-05 18:16 UTC by neonjonn

Send a neat little welcome card along with welcome messages

Preview:
![welcome card](https://media.discordapp.net/attachments/756939836144746608/917115709497155604/welcome.png)

2021-12-05 19:08 UTC, parafoxia requested changes
I'm on the train atm so haven't taken a proper look as such, but there are some things I can see now. I'll take a better look when I can, but here's some stuff to work on in the meantime (:

Also, you need to rebase this to get rid of those merge commits. A simple `git rebase` *might* fix things, but if not, one of us will need to do some finagling.

2021-12-05 19:08 UTC, parafoxia commented on requirements.txt
> +pillow>=8.4.0
This should be <9,>=8.4 to match the general requirements pattern.

2021-12-05 19:08 UTC, parafoxia commented on carberretta/extensions/gateway.py
> +    server_icon = Image.open("./data/static/server_icon.png").resize((80 * 4, 80 * 4))
This would ideally be fetched at runtime in the case of any server icon changes (for special events or rebrands).

2021-12-05 19:08 UTC, parafoxia commented on carberretta/extensions/gateway.py
> +    w = draw.textsize(text, font=FIRASANS_FONT)[0]
This would probably look prettier of you initially set w to a high number, then did all the drawing within the for loop, rather than have the draw operation written twice.

2021-12-05 19:08 UTC, parafoxia commented on carberretta/extensions/gateway.py
> +    mask = Image.open("./data/static/circle_mask.jpg")
I believe you can actually generate this in real-time, but I don't remember. I'm pretty sure in the series I didn't load a premade mask though. If this is faster, use this though.

2021-12-05 19:18 UTC, neonjonn commented on carberretta/extensions/gateway.py
> +    server_icon = Image.open("./data/static/server_icon.png").resize((80 * 4, 80 * 4))
Ah yeah, I'll fetch it on startup and add it to the plugin specific datastore 
(Should I also check for icon changes on guild update?)

2021-12-05 19:20 UTC, neonjonn commented on carberretta/extensions/gateway.py
> +    mask = Image.open("./data/static/circle_mask.jpg")
Yeah in the series you didn't, and I can easily put the mask generation code in there, I'll see which is faster

2021-12-05 19:20 UTC, parafoxia commented on carberretta/extensions/gateway.py
> +    server_icon = Image.open("./data/static/server_icon.png").resize((80 * 4, 80 * 4))
Yeah that's probably the best of doing it actually.

2021-12-05 19:21 UTC, parafoxia commented on carberretta/extensions/gateway.py
> +    mask = Image.open("./data/static/circle_mask.jpg")
Sounds good. If loading is faster just leave a comment here and resolve this I spose haha.

2021-12-05 19:27 UTC, neonjonn commented on carberretta/extensions/gateway.py
> +    mask = Image.open("./data/static/circle_mask.jpg")
I realised I could also just load the mask on startup and perform operations on it afterwards. And I could also do this for the curved border mask too, if you want.

2021-12-05 20:03 UTC, parafoxia commented on carberretta/extensions/gateway.py
> +    mask = Image.open("./data/static/circle_mask.jpg")
Yeah that'd probably be best. Real-time masks too, so they don't need to be stored and I think that'd work really well.

2021-12-05 20:08 UTC, neonjonn commented on carberretta/extensions/gateway.py
> +    mask = Image.open("./data/static/circle_mask.jpg")
So I'll go with creating them on startup and storing them in the plugin data store then?

2021-12-05 20:10 UTC, parafoxia commented on carberretta/extensions/gateway.py
> +    mask = Image.open("./data/static/circle_mask.jpg")
Yeah.

2021-12-16 12:40 UTC, parafoxia commented
Did you ever get round to redoing those changes? No worries if not, just doing a progress check.

2021-12-16 17:09 UTC, neonjonn commented
I think I have near-complete code somewhere, but I gotta pull the latest changes though and see what has to be complete first. Hopefully will have it done by Sunday :)

2021-12-17 17:21 UTC, parafoxia commented
Noice.

2022-01-18 20:42 UTC, closed without merging