Fixed RTFM Command
Carberra/Carberretta pull request #141
Opened 2022-04-07 21:15 UTC by Coler6gamer

2022-04-07 21:26 UTC, IkBenOlie5 requested changes

2022-04-07 21:26 UTC, IkBenOlie5 commented on carberretta/extensions/meta.py
> +    embed = hikari.Embed(title="RTFM", color=0x2F3136)
You probably want to use helpers.choose_color for this (same goes for the other embed)

2022-04-07 21:54 UTC, Jonxslays commented on carberretta/utils/rtfm.py
> +        cache[direct] = (match.groups(), link)
This feels weird.

It will check if match is in the cache dicts keys, but those keys are being set to direct and never the match itself.
Maybe I'm missing something, but I feel like that if statement may never be truthy.

2022-04-07 22:08 UTC, mshaugh requested changes
These changes would be better suited to a new extension at `carberretta/extensions/rtfm.py`.

_Note:_ Carberretta does not support prefix commands, so any such `lightbulb.implements` can be removed. Additionally, all `lightbulb.Context`s should be `lightbulb.SlashContext`s.

2022-04-07 22:10 UTC, Jonxslays commented
I added an error handler for `CommandNotFound` when I saw these were prefix commands as well. with no prefix commands that if isinstance block in the bot.py file should be removed from the error handler too.

2022-04-07 22:12 UTC, parafoxia requested changes
I've left some specifics around, but my general viewpoint is in line with Max's -- this should be it's own extension.

I recommend merging the RTFM functionality from the meta.py extension and the util into a single `rtfm.py` extension file and going from there. I'll provide a more detailed review when this is done, else it will get lost in a flood of changes.

2022-04-07 22:12 UTC, parafoxia commented on carberretta/__init__.py
> +LIGHTBULB_DOCS_URL: t.Final = "https://hikari-lightbulb.readthedocs.io/en/latest/"
These would be better off in the same file as the RTFM functionality.

2022-04-07 22:12 UTC, parafoxia commented on carberretta/bot.py
> +    bot.d.lightbulb_cache = rtfm.decode_object_inv(await lb.read())
Again, better off with the rest of it.

2022-04-07 22:12 UTC, parafoxia commented on carberretta/bot.py
> +
We're only supporting slash commands, so this is unnecessary.

2022-04-07 22:12 UTC, parafoxia commented on carberretta/extensions/meta.py
> +        mem_total = virtual_memory().total / (1024**2)
Did black format this?

2022-04-07 23:56 UTC, Coler6gamer commented on carberretta/utils/rtfm.py
> +        cache[direct] = (match.groups(), link)
I probably should have made more notes but I believe there could be some repeats and the if statement skips these. Idrk if the if statement ever gets run tbh.

2022-04-07 23:59 UTC, Coler6gamer commented on carberretta/__init__.py
> +LIGHTBULB_DOCS_URL: t.Final = "https://hikari-lightbulb.readthedocs.io/en/latest/"
I believe jonx changed up that part. I just put the link in with the session.get lol.

2022-04-07 23:59 UTC, Coler6gamer commented on carberretta/extensions/meta.py
> +        mem_total = virtual_memory().total / (1024**2)
No clue

2022-04-08 00:02 UTC, parafoxia commented on carberretta/extensions/meta.py
> +        mem_total = virtual_memory().total / (1024**2)
I spose if it's passing it's fine. Just different from now it normally does it I think.

2022-04-08 00:13 UTC, Jonxslays commented on carberretta/__init__.py
> +LIGHTBULB_DOCS_URL: t.Final = "https://hikari-lightbulb.readthedocs.io/en/latest/"
the reason i put them here is because they were used in the main bot file starting event and the rtfm file but if everything is getting moved to the rtfm extension it makes sense these should go there too.

2022-04-08 00:16 UTC, parafoxia commented on carberretta/__init__.py
> +LIGHTBULB_DOCS_URL: t.Final = "https://hikari-lightbulb.readthedocs.io/en/latest/"
Ah right, that makes sense.

2022-04-08 15:59 UTC, parafoxia requested changes

2022-04-08 15:59 UTC, parafoxia commented on carberretta/extensions/meta.py
> +plugin = lightbulb.Plugin("Meta", include_datastore=True)
This change can be reverted.

2022-04-08 15:59 UTC, parafoxia commented on requirements.txt
> +hikari==2.0.0.dev108
```suggestion
hikari[speedups]==2.0.0.dev108
```

2022-04-08 15:59 UTC, parafoxia commented on carberretta/extensions/rtfm.py
> +# Copyright (c) 2020-2021, Carberra Tutorials
```suggestion
# Copyright (c) 2020-2022, Carberra Tutorials
```

2022-04-08 15:59 UTC, parafoxia commented on carberretta/bot.py
> +    bot.d.lightbulb_cache = rtfm.decode_object_inv(await lb.read())
This still needs to be actioned.

2022-04-08 15:59 UTC, parafoxia commented on carberretta/extensions/rtfm.py
> +    regex = re.compile(r"(?x)(.+?)\s+(\S*:\S*)\s+(-?\d+)\s+(\S+)\s+(.*)")
This should be defined as a constant at the top of the file.

2022-04-08 17:56 UTC, parafoxia requested changes
Definitely getting closer! Just small things to change here.

If you're willing to, have a look into the possibility of getting the standard Python docs in. In theory it shouldn't be too much extra work, but there's every chance I'm wrong on that lmao.

Either way, good work so far.

2022-04-08 17:56 UTC, parafoxia commented on carberretta/__init__.py
> +LIGHTBULB_DOCS_URL: t.Final = "https://hikari-lightbulb.readthedocs.io/en/latest/"
These still need to be moved to the RTFM extension.

2022-04-08 17:56 UTC, parafoxia commented on carberretta/extensions/rtfm.py
> +regex = re.compile(r"(?x)(.+?)\s+(\S*:\S*)\s+(-?\d+)\s+(\S+)\s+(.*)")
```suggestion
CHUNK_REGEX = re.compile(r"(?x)(.+?)\s+(\S*:\S*)\s+(-?\d+)\s+(\S+)\s+(.*)")

plugin = lightbulb.Plugin("RTFM", include_datastore=True)
```
Constants are generally defined in all caps. The changes outlined in the suggestion will suffice here.

2022-04-08 17:56 UTC, parafoxia commented on carberretta/extensions/rtfm.py
> +                f"[`{match}`]({carberretta.HIKARI_DOCS_URL}"
Once you've moved the `HIKARI_DOCS_URL` constant here, remember to remove the `carberretta.`.

2022-04-08 17:56 UTC, parafoxia commented on carberretta/extensions/rtfm.py
> +                f"[`{match}`]({carberretta.LIGHTBULB_DOCS_URL}"
Same as above.

2022-04-08 17:56 UTC, parafoxia commented on carberretta/extensions/rtfm.py
> +        if not (match := regex.match(line.rstrip())):
```suggestion
        if not (match := CHUNK_REGEX.match(line.rstrip())):
```

2022-04-08 19:09 UTC, parafoxia reviewed
Everything looks okay at a glance, besides a slip-up with the requirements. I'd have to test it to fully approve it, but I can't see anything glaring that needs changing at this stage. Well done!

2022-04-08 19:09 UTC, parafoxia commented on requirements.txt
> +hikari==2.0.0.dev108
```suggestion
hikari[speedups]==2.0.0.dev108
```

2022-04-11 16:30 UTC, parafoxia requested changes
Mostly looks good at a glance, however:

- Some checks have failed -- make sure to remedy those
- There is still an outstanding change from a previous review

Fix those two points and everything should be alright.

2022-04-11 16:33 UTC, Coler6gamer commented
> * There is still an outstanding change from a previous review

Also, what was that outstanding change? I didn't see anything that I might have missed.

2022-04-11 16:45 UTC, parafoxia approved these changes
Approval is being made pending tests that I'm gonna do when I next can, but everything looks alright now!

Thanks Coler! Bet you're glad you made all those changes yourself now.

2022-04-12 15:42 UTC, merged