Fixed multiple bugs with RTFM
Carberra/Carberretta pull request #144
Opened 2022-04-14 15:35 UTC by Coler6gamer

- Fixed a bug from thommo's improvements.
- More relevant matches will go to the top of autocomplete/embed.
- Fixed links not being specific for functions.
- Fixed a few other kinks.

2022-04-14 16:41 UTC, mshaugh submitted a review, later dismissed

2022-04-14 16:41 UTC, mshaugh commented on carberretta/extensions/rtfm.py
>      return embed
Compute the description first and then return the embed.

```python
matches = await get_rtfm(query, cache)
description = []
for match in matches:
    ...

return hikari.Embed(
    title: "RTFM",
    description: "\n".join(description),
    ...
)
```

2022-04-14 16:41 UTC, mshaugh commented on carberretta/extensions/rtfm.py
> +    return pure_matches + match
Change the variable names.
I suggest: `matches` -> `extracted`, `match` -> `matches`.

2022-04-14 16:41 UTC, mshaugh commented on carberretta/extensions/rtfm.py
> +                description.append(f"[`{match}`]({url}{cache[match][1]})")
Improve readability with a `namedtuple` for cache entries.

2022-04-17 21:57 UTC, Coler6gamer commented
@parafoxia review please :)

2022-04-17 22:21 UTC, parafoxia requested changes
Just a small change, but other than that it looks fine to me. Would be worth @mshaugh re-reviewing this to make sure all his requested changes are sufficient in his eyes.

2022-04-17 22:21 UTC, parafoxia commented on carberretta/extensions/rtfm.py
> +        if direct in cache.keys():
```suggestion
        if direct in cache:
```

2022-04-18 11:07 UTC, parafoxia approved these changes

2022-05-26 14:13 UTC, parafoxia commented
@mshaugh, you still need to review this.

2022-09-18 14:15 UTC, merged