Feature/binify
Carberra/Carberretta pull request #150
Opened 2022-09-18 04:42 UTC by Jonxslays

This PR ports V1 `binify` command into V2 as a slash command.

This implementation accepts 2 arguments, the message snowflake and a number of days for when to expire the pastebin if there is one. The expires can be anything from 1-120 days.

Right now if a message isn't cached it will try to fetch, but only in the current channel.
I'm wondering if you can think of any better way to do that, like adding another option channel param maybe?

2022-09-18 04:52 UTC, Jonxslays commented
Oh, and I just put it in the `text` plugin since it seems like `support` isn't being ported anymore.

2022-09-18 07:55 UTC, parafoxia requested changes
This is just a cursory glance from my phone -- I'll do a proper review on the PC, but everything looks like it should be alright beyond these nitpicks.

2022-09-18 07:55 UTC, parafoxia commented on carberretta/extensions/text.py
> +    "The number of days before the bin will expire.",
"bin will expire" -> "paste expires"

2022-09-18 07:55 UTC, parafoxia commented on carberretta/extensions/text.py
> +    "snowflake", "The snowflake ID of the message to binify.", type=hikari.Snowflake
The type can be set directly to `hikari.Message` here. I *believe* this performs the checks you're doing automatically, though it occurs to me I've never tested that.

2022-09-18 07:55 UTC, parafoxia commented on carberretta/utils/string.py
> +            if not 200 <= response.status <= 299:
This can be `if not response.ok` I believe.

2022-09-18 07:56 UTC, parafoxia commented
> Oh, and I just put it in the `text` plugin since it seems like `support` isn't being ported anymore.

I think that's probably the best place for it for now.

2022-09-18 13:26 UTC, Jonxslays commented on carberretta/extensions/text.py
> +    "snowflake", "The snowflake ID of the message to binify.", type=hikari.Snowflake
I initially did try that but it was being weird in the client telling me the snowflake wasn't a valid input. Will take another look though.

2022-09-18 14:01 UTC, parafoxia commented on carberretta/extensions/text.py
> +    "snowflake", "The snowflake ID of the message to binify.", type=hikari.Snowflake
I have tried it and it definitely works (using a message ID), so long as you don't use the ID format where you have the `channel_id-message_id`.

2022-09-20 16:23 UTC, Jonxslays commented on carberretta/extensions/text.py
> +    "snowflake", "The snowflake ID of the message to binify.", type=hikari.Snowflake
It doesn't work, your implementation in clear is a `str` not a `hikari.Message`

2022-09-22 16:38 UTC, parafoxia requested changes
Generally smaller changes, overall it looks good. Once you've made these changes I'll pull the branch down locally and double check it looks good in use.

2022-09-22 16:38 UTC, parafoxia commented on carberretta/extensions/text.py
> +        ) or await ctx.bot.rest.fetch_message(ctx.channel_id, snowflake)
You can probably force black to format this in a way that isn't shit. Try putting the entire expression in brackets and it *should* format it better.

Another possible idea would be to take a leaf from Solaris' book and implement a `getch_message` in the bot object itself.

2022-09-22 16:38 UTC, parafoxia commented on carberretta/utils/string.py
> +from datetime import datetime, timedelta
Newer convention for this project is to do `import datetime as dt`, then access stuff from that.

2022-09-22 16:38 UTC, parafoxia commented on carberretta/utils/string.py
>  def possessive(user: Member | User) -> str:
I know you didn't do this, but this can be changed to just `User`. Might as well do that now seen as this function is called in your implementation.

2022-09-22 16:38 UTC, parafoxia commented on carberretta/utils/string.py
> +        async with session.put("https://api.mystb.in/paste", json=payload) as response:
Renaming `response` to `resp` would add consistency with the rest of the project. I think you did this before I used `resp`, but I do prefer that over `response`.

2022-09-22 16:50 UTC, parafoxia commented
If could also update the safety requirement to `~=2.2.0` to pass the check that'd be awesome. Don't set it to 2.2.1 as it will cause merge conflicts down the line.

2022-09-22 19:24 UTC, Jonxslays commented on carberretta/extensions/text.py
> +        ) or await ctx.bot.rest.fetch_message(ctx.channel_id, snowflake)
I'd go for the `getch_message`, but it would require subclassing `BotApp` because `__slots__`.
I could put it in `bot.d` if you wanted but that seems weird to me for some reason.
Black still reformats it when you wrap it in parens, but adding a comment inside them stops it :kek:

2022-09-22 19:34 UTC, Jonxslays commented
I just rebased onto main and got the update to safety that you did ^.^

2022-09-23 00:25 UTC, parafoxia approved these changes

2022-09-23 00:25 UTC, merged