Port YouTube cog
Carberra/Carberretta pull request #152
Opened 2022-09-21 03:34 UTC by parafoxia

This PR ports the YouTube cog into V2.

Currently, the following tasks have been completed:

* Create a `link` command, which allows users to search for a video using the title (and autocomplete) and return a link

2022-09-21 03:35 UTC, Jonxslays commented
Add a daily recurring task to check for new videos until a more robust implementation is in place.

2022-09-21 03:38 UTC, parafoxia commented on carberretta/extensions/youtube.py
> +    videos = scrapetube.get_channel(Config.YOUTUBE_CHANNEL_ID)
Somehow run all this stuff in an executor.

2022-09-21 03:41 UTC, parafoxia commented on carberretta/extensions/youtube.py
> +async def cmd_youtube_link(ctx: lightbulb.SlashContext) -> None:
Add option to set the maximum number of results displayed (min = 5/10, max=25, default=10).

2022-09-21 17:56 UTC, Jonxslays submitted a review, later dismissed
looks good

2022-09-22 12:49 UTC, parafoxia commented on carberretta/bot.py
> +    cookie_jar = CookieJar(loop=asyncio.get_running_loop())
These cookies can be removed.

2022-09-22 19:12 UTC, Jonxslays requested changes
Mostly also nit picks, but 1 cmd description change.

2022-09-22 19:12 UTC, Jonxslays commented on carberretta/extensions/youtube.py
> +BROWSE_ENDPOINT = "https://www.youtube.com/youtubei/v1/browse"
I feel like this url should match the one below without the www

2022-09-22 19:12 UTC, Jonxslays commented on carberretta/extensions/youtube.py
> +def _similarity(s1: str, s2: str, **_: t.Any) -> float:
Is there a particular reason you accept kwargs here but discard them?
I assume something to do with the args rapidfuzz passes but maybe worth a comment?

2022-09-22 19:12 UTC, Jonxslays commented on carberretta/extensions/youtube.py
> +        f"https://www.youtube.com/channel/{Config.YOUTUBE_CHANNEL_ID}/"
Same as above with the www, maybe you should just extract the base URL into its own var.

2022-09-22 19:12 UTC, Jonxslays commented on carberretta/extensions/youtube.py
> +@lightbulb.command("information", "View information about an video.")
```suggestion
@lightbulb.command("information", "View information about a video.")
```

2022-09-22 19:12 UTC, Jonxslays commented on carberretta/extensions/youtube.py
> +        return dur.replace("H", "h ").replace("M", "' ").replace("S", '"')[2:]
lambda?

2022-09-22 19:35 UTC, parafoxia commented on carberretta/extensions/youtube.py
> +BROWSE_ENDPOINT = "https://www.youtube.com/youtubei/v1/browse"
Yeah probably, good spot.

2022-09-22 19:35 UTC, parafoxia commented on carberretta/extensions/youtube.py
> +def _similarity(s1: str, s2: str, **_: t.Any) -> float:
Yeah it passes some kwargs we don't need so I just consume them all.

2022-09-22 19:36 UTC, parafoxia commented on carberretta/extensions/youtube.py
> +        f"https://www.youtube.com/channel/{Config.YOUTUBE_CHANNEL_ID}/"
I'm not sure since it never needs to be suffixed with anything.

2022-09-22 19:43 UTC, Jonxslays commented on carberretta/extensions/youtube.py
> +        f"https://www.youtube.com/channel/{Config.YOUTUBE_CHANNEL_ID}/"
It's used a few times throughout the code with different suffixes like `/youtubei/...`, `/channel/...` and `/watch?...`. in any case not a big deal.

2022-09-23 00:08 UTC, parafoxia commented on carberretta/extensions/youtube.py
> +BROWSE_ENDPOINT = "https://www.youtube.com/youtubei/v1/browse"
So the WWW here is necessary -- without it, it completely breaks. How odd. I've just added WWW to them all now lmao.

2022-09-23 00:17 UTC, Jonxslays approved these changes
`MINE_URL` is sussy

2022-09-23 00:19 UTC, parafoxia commented
It's consistent with how all YouTube APIs typically denote "your something" in authorised requests (passing "MINE" as a parameter tells it to use your channel ID).

2022-09-23 00:25 UTC, merged