CronJob & dev updates
Carberra/Carberretta pull request #163
Opened 2022-10-26 11:49 UTC by Aoi-Yuito

Sorry man! I accidentally deleted the previous PR to delete a single message sent by mistake. My bad! I am new to these stuffs. Well anyways, as you have told me earlier to set a CronTrigger to refresh the caches and also to update the requirements-dev.txt.
All is done but I am not sure about the requirements-dev.txt Did I do something wrong while updating the dev file?

2022-10-26 12:01 UTC, Aoi-Yuito commented
Alright I understood what you meant by to update the requirements-dev.txt.

2022-10-26 12:02 UTC, parafoxia commented
For the requirements (and more generally the checks as a whole), if you do `pip install nox` then run `nox`, you'll run the checks. Running `nox -s dependencies` will tell you which requirements need to be updated in the files, and to what versions.

I would reset the requirements file to what was there before, then run the nox check, and make the changes it recommends.

I'll be able to check the rest of it when I'm on my computer. Though those nox checks should inform you how to fix your formatting and import errors.

2022-10-26 12:07 UTC, Aoi-Yuito commented
No worries! I fixed the dependency error but I am clueless about the import errors.

2022-10-26 12:36 UTC, parafoxia commented
Looks like you fixed them lmao. One of the times it fails is if they're not formatted correctly, so fixing the formatting can sometimes fix the imports too, which is what's happened here. Changes you've made in the last commit look good.

2022-10-28 15:50 UTC, parafoxia requested changes

2022-10-28 15:50 UTC, parafoxia commented on carberretta/extensions/rtfm.py
>      plugin.bot.d.python_cache = decode_object_inv(await py.read())
These two lines can be removed.

2022-10-28 15:50 UTC, parafoxia commented on carberretta/extensions/rtfm.py
> +
This command can be removed now it's done automatically.

2022-10-29 16:43 UTC, Aoi-Yuito commented on carberretta/extensions/rtfm.py
> +
ahh...well, I kept the command for emergency cases for example -> right after triggering this CronJob, the libs got updated. Then we will get the latest cache 6 hours later. Wouldn't it be a problem? That's why I kept it but should I still remove the command?

2022-10-29 17:16 UTC, parafoxia commented on carberretta/extensions/rtfm.py
> +
If you want it every 6 hours, it needs to be `hour="0,6,12,18"` -- it's currently set to only run at 6am every day. But yeah we it doesn't matter if it's a few hours late to update.

2022-10-29 18:04 UTC, Aoi-Yuito commented on carberretta/extensions/rtfm.py
> +
Alright, done!

2022-10-29 22:32 UTC, parafoxia requested changes

2022-10-29 22:32 UTC, parafoxia commented on carberretta/extensions/rtfm.py
> +    plugin.bot.d.lightbulb_cache = decode_object_inv(await lb.read())
I think I did say these lines can be removed didn't I? If you want to call it on boot, which might be a good idea tbh, just call the function.

2022-10-30 03:02 UTC, Aoi-Yuito commented on carberretta/extensions/rtfm.py
> +    plugin.bot.d.lightbulb_cache = decode_object_inv(await lb.read())
Ohh, sorry, I misunderstand. Working on it...

2022-10-30 03:06 UTC, Aoi-Yuito commented on carberretta/extensions/rtfm.py
> +    plugin.bot.d.lightbulb_cache = decode_object_inv(await lb.read())
Done!

2022-11-03 18:18 UTC, parafoxia approved these changes

2022-11-03 18:19 UTC, merged