Filter System
Carberra/Carberretta pull request #44
Opened 2020-10-15 23:45 UTC by MrDogeBro

* Closes #6

2020-10-16 00:29 UTC, parafoxia requested changes
Good PR! Overall looks pretty sound, most suggestions made are PEP 8 standards, etc.

However, you do need to update the dependencies and the config files. Run `poetry add content_filter` in the terminal to add that dependency, and add any extra config IDs (such as the `MODLOG_ID`) to the docker-compose.yml file.

2020-10-16 00:29 UTC, parafoxia commented on carberretta/utils/chron.py
> +from json import JSONEncoder
Alphabetise imports as per PEP 8 standards.
```suggestion
from json import JSONEncoder
from time import strftime
```

2020-10-16 00:29 UTC, parafoxia commented on carberretta/utils/chron.py
> +            return obj.isoformat()
I would say place this above `sys_time` on line 7.

2020-10-16 00:29 UTC, parafoxia commented on carberretta/bot/cogs/mod.py
>  from discord.ext import commands
PEP 8 imports.
```suggestion
import datetime as dt
import json
import string
import typing as t
from collections import defaultdict
from os import path

import aiofiles
import discord
from content_filter import checkMessageList, useCustomListFile, updateListFromFile
from discord.ext import commands
```

2020-10-16 00:29 UTC, parafoxia commented on carberretta/bot/cogs/mod.py
> +from carberretta.utils import chron, DEFAULT_EMBED_COLOUR
```suggestion
from carberretta.utils import DEFAULT_EMBED_COLOUR, chron
```

2020-10-16 00:29 UTC, parafoxia commented on carberretta/bot/cogs/mod.py
> +                warning_msg = await message.channel.send(f"{message.author.mention} please do not use offensive language!")
```suggestion
                warning_msg = await message.channel.send(f"{message.author.mention}, please do not use offensive language.")
```

2020-10-16 00:29 UTC, parafoxia commented on carberretta/bot/cogs/mod.py
> +                            "image": {"url": att[0].url if len((att := message.attachments)) else None},
You don't need the `len(...)` call here.
```suggestion
                            "image": {"url": att[0].url if (att := message.attachments) else None},
```

2020-10-16 00:29 UTC, parafoxia commented on carberretta/bot/cogs/mod.py
> +                                    "value": f'[Jump to Message](https://discordapp.com/channels/{message.guild.id}/{message.channel.id}/{warning_msg.id})', "inline": False},
`Message` objects have a `jump_url` attribute: https://discordpy.readthedocs.io/en/latest/api.html?highlight=file#discord.Message.jump_url

2020-10-16 00:29 UTC, parafoxia commented on carberretta/bot/cogs/mod.py
> +                await f.write(json.dumps(filter_data, indent=4, cls=chron.DateTimeEncoder))
The `indent` kwarg isn't necessary unless the user is going to see the file.
```suggestion
                await f.write(json.dumps(filter_data, cls=chron.DateTimeEncoder))
```

2020-10-16 00:29 UTC, parafoxia commented on carberretta/bot/cogs/mod.py
> +                await f.write(json.dumps(filter_file_template, indent=4, cls=chron.DateTimeEncoder))
Same as line 212.

2020-10-16 00:29 UTC, parafoxia commented on carberretta/bot/cogs/mod.py
> +            await f.write(json.dumps(filter_data, indent=4, cls=chron.DateTimeEncoder))
Same as line 212.

2020-10-16 00:29 UTC, parafoxia commented on carberretta/bot/cogs/mod.py
> +            await f.write(json.dumps(filter_data, indent=4, cls=chron.DateTimeEncoder))
Same as line 212.

2020-10-16 00:29 UTC, parafoxia commented on carberretta/bot/cogs/mod.py
> +            await f.write(json.dumps(filter_data, indent=4, cls=chron.DateTimeEncoder))
Same as line 212.

2020-10-16 00:29 UTC, parafoxia commented on carberretta/bot/cogs/mod.py
> +            await f.write(json.dumps(filter_data, indent=4, cls=chron.DateTimeEncoder))
Same as line 212.

2020-10-16 00:29 UTC, parafoxia commented on carberretta/bot/cogs/mod.py
> +            await f.write(json.dumps(filter_data, indent=4, cls=chron.DateTimeEncoder))
Same as line 212.

2020-10-16 00:29 UTC, parafoxia commented on carberretta/bot/cogs/mod.py
> +            await f.write(json.dumps(filter_data, indent=4, cls=chron.DateTimeEncoder))
Same as line 212.

2020-10-16 01:02 UTC, MrDogeBro commented on carberretta/bot/cogs/mod.py
> +                                    "value": f'[Jump to Message](https://discordapp.com/channels/{message.guild.id}/{message.channel.id}/{warning_msg.id})', "inline": False},
Thanks for that info — looked around but couldn't find this but there it is

2020-10-16 03:02 UTC, MrDogeBro commented on carberretta/bot/cogs/mod.py
> +                            "image": {"url": att[0].url if len((att := message.attachments)) else None},
Fixed where it was copied from your code above as well

2020-10-16 03:53 UTC, MrDogeBro commented
Ok all changes should be updated as per request. Wouldn't be a bad idea for you to go through and check that they are all in place how you would like them to be though.

2020-10-16 21:58 UTC, MrDogeBro commented
Just added the ability for the user to specify if a word in the conditional filter needs to have a space in front of the word or not for the conditional filter to pick up on the word.

2020-10-17 16:00 UTC, parafoxia approved these changes
Just the one really simple thing, but I'm pretty sure I can commit it on my end. Thanks for the contribution!

2020-10-18 12:20 UTC, parafoxia submitted a review, later dismissed

2020-10-20 15:49 UTC, mshaugh requested changes
Please revert changes made to:

* `carberretta/bot/cogs/support.py`
* `carberretta/bot/cogs/youtube.py`
* `carberretta/bot/utils/string.py`

In the same vein, please also clean up the git history by removing some of the 'useless' commits (e.g. 
23b1426).

Additionally, please undo the version change in `pyproject.toml`.

To do this:

```shell
$ git checkout filterSystem
$ git rebase -i HEAD~n # where n is the number of last commits you want to include in interactive rebase.
# Replace pick with drop for commits you want to discard.
# Save and exit.
$ git push --force
```

To be clear, the pull request should only contain changes directly related to the feature: its documentation, implementation, dependencies, and so forth.

As for `carberretta/bot/cogs/mod.py`:

* Prefer the use of [`pathlib`](https://docs.python.org/3/library/pathlib.html) over `os.path`
* Use [`str.translate`](https://docs.python.org/3/library/stdtypes.html#str.translate) instead of long `replace` chains
* I don't see the necessity of the `fix_x_y` functions in `load_filter_file`
* Much of the logic can be inverted to improve readability
    ```python
    # Bad
    if condition:
        do_something()
    else:
        error()

    # Good:
    if not condition:
        error()
    
    do_something()
    ```
* Use [`del`](https://docs.python.org/3/reference/simple_stmts.html#the-del-statement), rather than creating a list of keys to remove
* Generalise 'word_found' logic to a single function
    * Currently, it is repeated across many functions with slight differences. It shouldn't be too hard to generalise, returning the found word or raising appropriate exceptions.
* It is trivial to bypass the filter
    * Non-English characters (e.g. [ϲ](https://en.wikipedia.org/wiki/Sigma#Lunate_sigma), [ç](https://en.wikipedia.org/wiki/%C3%87) instead of [c](https://en.wikipedia.org/wiki/C))
    * Non-printing characters (e.g. [ZWSP](https://en.wikipedia.org/wiki/Zero-width_space))


As an aside, and this is most certainly not a required change, please consider patching [content_filter](https://pypi.org/project/content-filter/) to be more PEP8 compliant. Specifically [function names](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names) should be snake case (lowercase_with_underscores)

2020-11-01 01:02 UTC, MrDogeBro commented
- [ ] Update to use `pathlib` over `os.path`
- [ ] Use `str.translate` over replace chains
- [ ] Generalise 'word_found' logic to a single function
- [ ] Remove useless commits
- [ ] Invert logic for readability
- [ ] Improve filtering in `content_filter` module
  - [Non-English](https://github.com/MrDogeBro/content_filter/issues/2) charaters
  - [Non-printing](https://github.com/MrDogeBro/content_filter/issues/3) charaters
- [ ] Make `content_filter` [comply with PEP8](https://github.com/MrDogeBro/content_filter/issues/4)

2020-12-22 20:09 UTC, MrDogeBro commented
Ok, so changes have been made now. I think that everything you wanted @mshaugh has been changed. If either of you two see anything I missed just tell me and I'll fix it. If you'd like anything else changed just tell me as well. Also sorry for the long delay. I've been busy and working on other stuff recently.

2020-12-22 20:13 UTC, parafoxia commented
It's okay, we've been busy too. We still need to review Carberretta's infrastructure for the v2 release, so we'll review the changes after that's complete.

2021-03-27 22:41 UTC, MrDogeBro commented
The feature has been added so that an automod action can be specified. The default action is just a warning but you can set an individual word to be a warn, kick, or ban when detected. Currently it is just a verbal warning but in the future this will integrate with the new moderation system for Carberretta v2 so that the warnings actually count and the kick and ban actually kick or ban the person. When the new moderation system is introduced, I can help with integrating the filter auto mod into it if needed/wanted.

2021-03-28 21:26 UTC, MrDogeBro commented
I added a verbal warn action and the verbal warn action is now the default if an action is not provided. This will integrate into the new verbal/zero warn system for Carberretta in the future.

2021-11-26 15:31 UTC, closed without merging

2021-12-05 13:41 UTC, parafoxia commented
Superceded by #137.