Add Google Command
Carberra/Carberretta pull request #79
Opened 2021-05-02 13:03 UTC by JohnnyJTH

2021-05-02 13:09 UTC, parafoxia approved these changes
A few minor changes, but I can handle them on this end. Good work!

2021-05-02 13:09 UTC, parafoxia commented on carberretta/bot/cogs/links.py
> +    async def command_google(self, ctx, *, query):
```suggestion
    async def command_google(self, ctx: commands.Context, *, query: str) -> None:
```

2021-05-02 13:09 UTC, parafoxia commented on carberretta/bot/cogs/links.py
> +            return await ctx.send("Please keep the query under 500 characters")
```suggestion
            return await ctx.send("Your query should be no longer than 500 characters.")
```

2021-05-02 13:10 UTC, parafoxia submitted a review, later dismissed

2021-05-05 22:21 UTC, parafoxia requested changes
Remove the meme command from this PR.

2021-05-06 06:48 UTC, JohnnyJTH commented
> Remove the meme command from this PR.

I tried but I can't. I'll just make a new PR because on my current fork the meme command is gone but this wont update

2021-05-06 06:53 UTC, JohnnyJTH commented
https://github.com/Carberra/Carberretta/pull/83

2021-05-06 06:53 UTC, closed without merging

2021-05-06 08:33 UTC, parafoxia commented
> I tried but I can't. I'll just make a new PR because on my current fork the meme command is gone but this wont update

#80 was closed already. You should not make a new PR with a meme command.