added Hug command
Carberra/Carberretta pull request #87
Opened 2021-05-07 05:14 UTC by namanyt

`+hug` will send a embed with a hug embed as shown in the image
<img width="329" alt="Screen Shot 2021-05-07 at 10 44 15 AM" src="https://user-images.githubusercontent.com/69317068/117400898-2be2d680-af21-11eb-9037-a4f6a141db4d.png">

`+huglb` will send this leaderboard type embed
<img width="331" alt="Screen Shot 2021-05-07 at 10 44 43 AM" src="https://user-images.githubusercontent.com/69317068/117400931-3c934c80-af21-11eb-8b43-bbbd1a37cb9e.png">

2021-05-07 05:17 UTC, namanyt commented
this is for a issue#64

2021-05-07 15:28 UTC, mshaugh requested changes

2021-05-07 15:28 UTC, mshaugh commented on .gitignore
> +.vscode/
Do not change the `.gitignore`

2021-05-07 15:28 UTC, mshaugh commented on carberretta/bot/cogs/misc.py
> +from discord.ext.commands import BucketType
`discord.ext.commands` is already imported, no need to import BucketType here.

2021-05-07 15:28 UTC, mshaugh commented on carberretta/bot/cogs/misc.py
> +class Leaderboard(ListPageSource):
Bot does not need to be passed in here, it is never used.
Remove `write_page`, and just use `format_page` to do all of the work.
Prefer `Embed.from_dict`.
Use type hints.

2021-05-07 15:28 UTC, mshaugh commented on carberretta/bot/cogs/misc.py
> +    async def hug_user_command(self, ctx: commands.Context, user: discord.Member):
Adhere to PEP8 standards.
Variable names need to be more meaningful.
Prefer `command_x` naming scheme.
Prefer `Embed.from_dict`.
Use type hints.

2021-05-07 15:28 UTC, mshaugh commented on carberretta/data/static/build.sql
> +CREATE TABLE IF NOT EXISTS hugLeaderboard (
Call the table `hugs`
Prefer `given` and `received` to `TimesHuggedOthers` and `TimesGotHugs`.

2021-05-07 15:32 UTC, namanyt commented on .gitignore
> +.vscode/
I actually did it cus my vscode was sending notification for adding this, as I added to gitignore to ignore it

2021-05-07 16:15 UTC, parafoxia commented on .gitignore
> +.vscode/
Just don't commit the folder.

2021-05-07 16:22 UTC, namanyt commented on .gitignore
> +.vscode/
ok

2021-05-07 16:37 UTC, mshaugh commented on .gitignore
> +.vscode/
Use a "global" gitignore. See https://git-scm.com/docs/gitignore and `core.excludesFile`.

2021-05-08 00:02 UTC, parafoxia requested changes

2021-05-08 00:02 UTC, parafoxia commented on carberretta/bot/cogs/misc.py
> +        await self.bot.db.execute('UPDATE hugLeaderboard SET received = received + 1 WHERE UserID = ?', user_id)
Combine SQL statements.

2021-05-08 00:02 UTC, parafoxia commented on carberretta/bot/cogs/misc.py
> +        await self.bot.db.commit()
Not needed.

2021-05-08 00:02 UTC, parafoxia commented on carberretta/data/static/build.sql
> +    given INTEGER DEFAULT 0
```suggestion
    Received INTEGER DEFAULT 0,
    Given INTEGER DEFAULT 0
```

2021-05-08 01:55 UTC, namanyt commented on carberretta/bot/cogs/misc.py
> +        await self.bot.db.commit()
It is needed as I found it was not committing anything to the data base from this cog

2021-05-08 02:17 UTC, parafoxia commented on carberretta/bot/cogs/misc.py
> +        await self.bot.db.commit()
It should automatically commit using the scheduled task. It is does not, you need to look into why.

2021-05-08 09:14 UTC, namanyt commented on carberretta/data/static/build.sql
> +    given INTEGER DEFAULT 0
ok

2021-05-08 22:16 UTC, parafoxia requested changes
The single change you've made is fine, but there are still multiple outstanding comments that have not been resolved.

2021-11-26 15:31 UTC, closed without merging