added experience system
Carberra/Carberretta pull request #88
Opened 2021-05-07 08:31 UTC by IkBenOlie5

#11

2021-05-07 15:38 UTC, mshaugh requested changes

2021-05-07 15:38 UTC, mshaugh commented on .gitignore
> +# pycharm
Do not change the `.gitignore`

2021-05-07 15:38 UTC, mshaugh commented on carberretta/bot/cogs/leveling.py
> +class Leveling(commands.Cog):
Levelling.
Remove the dateutil dependency, it is not needed.
Prefer `command_x` naming scheme.

2021-05-07 15:38 UTC, mshaugh commented on carberretta/bot/cogs/leveling.py
> +    def calculate_next_level(lvl: int) -> int:
This function name is unclear. Calculating the next level from level X is trivial... it's X+1.

2021-05-07 15:38 UTC, mshaugh commented on carberretta/bot/bot.py
> +            await self.db.execute("INSERT OR IGNORE INTO users (UserID) VALUES (?)", message.author.id)
Remove this and use UPSERT in the implementation.

2021-05-07 15:38 UTC, mshaugh commented on carberretta/data/static/build.sql
> +    Level int DEFAULT 0,
We can calculate the level from the experience, no need to store it in the database.

2021-05-07 15:38 UTC, mshaugh commented on carberretta/bot/cogs/leveling.py
> +    async def togglelevelmessage_command(self, ctx: commands.Context):
Leverage SQL to do the toggling, the SELECT is completely unnecessary.

2021-05-07 15:45 UTC, IkBenOlie5 commented on carberretta/bot/cogs/leveling.py
> +class Leveling(commands.Cog):
oh i assumed it was x_command since the feeds cog has it that way

2021-05-07 15:47 UTC, IkBenOlie5 commented on carberretta/bot/bot.py
> +            await self.db.execute("INSERT OR IGNORE INTO users (UserID) VALUES (?)", message.author.id)
ok, didnt know it existed

2021-05-07 16:13 UTC, IkBenOlie5 commented on .gitignore
> +# pycharm
why?

2021-05-07 16:17 UTC, parafoxia commented on .gitignore
> +# pycharm
It's based on a template, from which IDE-specific ignores were removed. You should either not commit PyCharm files, or create your own local .gitignore for this (preferably the latter -- it's easier in the long run).

2021-05-07 16:18 UTC, IkBenOlie5 commented on .gitignore
> +# pycharm
ill add .gitignore to the .gitignore lmao

2021-05-07 16:40 UTC, mshaugh commented on .gitignore
> +# pycharm
Use a "global" gitignore. See https://git-scm.com/docs/gitignore and `core.excludesFile`.

2021-05-07 16:42 UTC, mshaugh commented on carberretta/bot/cogs/leveling.py
> +    async def togglelevelmessage_command(self, ctx: commands.Context):
`UPDATE ... RETURNING ...`

2021-05-07 16:46 UTC, IkBenOlie5 commented on carberretta/bot/cogs/leveling.py
> +    async def togglelevelmessage_command(self, ctx: commands.Context):
oh, i thought i couldnt use returning, but sure

2021-05-08 03:07 UTC, parafoxia commented on carberretta/bot/cogs/leveling.py
> +    def calculate_next_level(lvl: int) -> int:
`get_required_xp` will work.

2021-05-08 07:02 UTC, IkBenOlie5 commented on carberretta/bot/cogs/leveling.py
> +    def calculate_next_level(lvl: int) -> int:
ok!

2021-05-08 22:01 UTC, parafoxia commented on carberretta/bot/cogs/experience.py
> +                                                     """, message.author.id, randint(1, 20), message.author.id)
Avoid using triple quotes here. Instead, use brackets to merge multiple strings together:
```py
(
    "This will "
    "be treated as "
    "one string"
)
```

2021-05-08 22:01 UTC, parafoxia commented on carberretta/bot/cogs/experience.py
> +                                    delete_after=10, mention_author=False)
Use the `black` beautifier.

2021-05-08 22:02 UTC, parafoxia commented on carberretta/bot/cogs/experience.py
> +                await message.reply(f"{message.author.display_name}, you leveled up! You are now level `{new_lvl}`.",
```suggestion
                await message.reply(f"{message.author.display_name}, you leveled up! You are now level {new_lvl}.",
```

2021-05-08 22:02 UTC, parafoxia commented on carberretta/data/static/build.sql
> +    MemberID int NOT NULL PRIMARY KEY,
Revert this back to `UserID`.

2021-05-08 22:03 UTC, parafoxia commented on carberretta/bot/cogs/experience.py
> +import typing
```suggestion
import typing as t
```
Don't forget to change other instances.

2021-05-08 22:03 UTC, parafoxia commented on carberretta/bot/cogs/experience.py
> +    @commands.command(name="togglelevelmessage", aliases=["togglelvlmsg", "lvluplog"])
```suggestion
    @commands.command(name="togglelevelmessage", aliases=["togglelvlmsg", "lvluplog", "lvlupmsg"])
```

2021-05-08 22:04 UTC, parafoxia commented on carberretta/bot/cogs/experience.py
> +            return
```suggestion
            return await ctx.send(f"{member.display_name} is not in the database.")
```

2021-05-08 22:05 UTC, parafoxia commented on carberretta/bot/cogs/experience.py
> +        await ctx.send(f"{member.display_name} has `{lvl}` levels. (`{exp}/{required_exp}`)")
```suggestion
        await ctx.send(f"{member.display_name} is on level {lvl}. Progress to next level: {exp}/{required_exp}.")
```

2021-05-08 22:06 UTC, parafoxia commented on carberretta/bot/cogs/experience.py
> +    @commands.command(name="leveltop", aliases=["ranktop", "lvltop", "experiencetop", "exptop", "xptop"])
I feel like this should contain some aliases that use leaderboard or lb somewhere. Maybe `xplb`.

2021-05-08 22:07 UTC, parafoxia commented on carberretta/data/static/build.sql
> +    LastUpdate datetime DEFAULT CURRENT_TIMESTAMP
`boolean` and `datetime` do not exist in SQLite3. They should be `integer` and `numeric` respectively. The `int` fields should also be `integer`.

2021-05-09 06:22 UTC, IkBenOlie5 commented on carberretta/data/static/build.sql
> +    MemberID int NOT NULL PRIMARY KEY,
also the table name?

2021-05-09 06:24 UTC, IkBenOlie5 commented on carberretta/data/static/build.sql
> +    LastUpdate datetime DEFAULT CURRENT_TIMESTAMP
the premieres table uses int too, so i thought i used what they used

2021-05-09 06:29 UTC, IkBenOlie5 commented on carberretta/bot/cogs/experience.py
> +                                    delete_after=10, mention_author=False)
ok, i just used autopep8

2021-11-26 15:31 UTC, closed without merging