Added Guild Event Logging
Carberra/Carberretta pull request #92
Opened 2021-05-07 15:37 UTC by JohnnyJTH

Logs the following events:
    Nickname Add
    Nickname Remove
    Nickname Change

    Message Delete
    Message Edit
    Bulk Message Delete

    Role Add
    Role Remove

    Member Join
    Member Leave

`self.log_channel` needs to be adjusted before production.

2021-05-07 15:38 UTC, JohnnyJTH commented
Resolved https://github.com/Carberra/Carberretta/issues/10

2021-05-07 23:52 UTC, parafoxia requested changes
There's quite a bit of unnecessary code here. You also need to be utilising the config.

2021-05-07 23:52 UTC, parafoxia commented on carberretta/bot/cogs/logging.py
> +import mystbin # pip install mystbin.py
We use `aiohttp` to make requests to Mystbin -- use the `self.bot.session` provided to do so. Look at the binify command for inspiration.

2021-05-07 23:52 UTC, parafoxia commented on carberretta/bot/cogs/logging.py
> +        self.log_channel = 762427685556191283
This should be in the config, and set as the channel object, not just the ID.

2021-05-07 23:52 UTC, parafoxia commented on carberretta/bot/cogs/logging.py
> +                )
Prefer `Embed.from_dict`.

2021-05-07 23:52 UTC, parafoxia commented on carberretta/bot/cogs/logging.py
> +                await channel.send(embed=embed)
A lot of this code is unnecessary. It would be better to change some variables using the if statements, then construct the embed using these variables, rather than have three almost identical builders.

2021-05-07 23:52 UTC, parafoxia commented on carberretta/bot/cogs/logging.py
> +            old = [roles for roles in before.roles if roles not in after.roles]
```suggestion
            new = set(after.roles) - set(before.roles)
            old = set(before.roles) - set(after.roles)
```
Or maybe...
```suggestion
            diff = set(before.roles) ^ set(after.roles)
            added = len(after.roles) > len(before.roles)  # Returns a boolean
```

2021-05-07 23:52 UTC, parafoxia commented on carberretta/bot/cogs/logging.py
> +                          ("Message Content #2", message.content[1000:], False)]
Run the black beautifier:

```bash
pip install black
black . -l119
```

2021-05-07 23:52 UTC, parafoxia commented on carberretta/bot/cogs/logging.py
> +        except Exception as e:
Carberretta has error handlers of it's own. We would want to raise this.

2021-05-07 23:52 UTC, parafoxia commented on carberretta/bot/cogs/logging.py
> +        self.min_days = 7
This would better defined as a constant after the imports:
```py
MIN_DAYS = 7
```

2021-05-07 23:52 UTC, parafoxia commented on carberretta/bot/cogs/logging.py
> +        embed.description = f"{warn}User: {member.mention}\nAccount Created On: {member.created_at.strftime('%d %b %Y %H:%M')} ({days} days ago)"
```suggestion
        embed.description = f"{warn}User: {member.mention}\nAccount created on: {member.created_at.strftime('%d %b %Y %H:%M')} ({days} days ago)"
```

2021-08-23 05:49 UTC, JohnnyJTH commented
I kind of forgot about this. Should I fix the issues or is it not worth it

2021-08-23 18:25 UTC, parafoxia commented
It won't be merged until v2.0 now, which will use hikari. It's up to you whether you want to keep it open and work with the new changes when they come.

2021-11-26 15:31 UTC, closed without merging