optimize database calls in feeds cog
Carberra/Carberretta pull request #95
Opened 2021-05-08 02:06 UTC by Jonxslays

- remove unnecessary db calls from for loop in `get_new_premieres()`.
- remove unnecessary calls to commit the db - 1min auto commit already scheduled.
- combine sql statements where possible.

This should significantly reduce the number of database calls.

2021-05-08 22:13 UTC, parafoxia requested changes

2021-05-08 22:13 UTC, parafoxia commented on carberretta/bot/cogs/feeds.py
> +            if data["is_live"] and not int(live_now):
No need to convert to `int` here.

2021-05-08 22:13 UTC, parafoxia commented on carberretta/bot/cogs/feeds.py
> +                    message = await self.videos_channel.fetch_message(int(stream_message))
SQLite should return an `int` automatically if it were stored as such.

2021-05-08 22:15 UTC, Jonxslays commented on carberretta/bot/cogs/feeds.py
> +                    message = await self.videos_channel.fetch_message(int(stream_message))
the ContentValue field in the database stores text. This is why i have converted to int.

2021-05-08 22:26 UTC, Jonxslays commented on carberretta/bot/cogs/feeds.py
> +                    message = await self.videos_channel.fetch_message(int(stream_message))
working on some adjustments for this.

2021-05-12 00:05 UTC, parafoxia requested changes
Everything looks okay functionally, but it looks like you haven't run the `black` beautifier. Run `black . -l119` and commit only this file if there are any changes. If there aren't any, let me know and I'll approve it.

2021-05-12 01:10 UTC, Jonxslays commented
I've run the beautifier now. Should be good to go.

2021-05-13 18:05 UTC, parafoxia approved these changes

2021-05-14 18:03 UTC, merged